
-- Create Notices Table
CREATE TABLE IF NOT EXISTS notices (
    id bigint generated by default as identity primary key,
    title text NOT NULL,
    content text NOT NULL,
    author text DEFAULT 'Admin',
    is_pinned boolean DEFAULT false,
    active boolean DEFAULT true,
    view_count integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- Create FAQs Table
CREATE TABLE IF NOT EXISTS faqs (
    id bigint generated by default as identity primary key,
    category text NOT NULL, -- 'general', 'technical', 'billing', 'service'
    question text NOT NULL,
    answer text NOT NULL,
    sort_order integer DEFAULT 0,
    active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- Create Inquiries Table (for 1:1 contact form)
CREATE TABLE IF NOT EXISTS inquiries (
    id bigint generated by default as identity primary key,
    name text NOT NULL,
    phone text NOT NULL,
    email text NOT NULL,
    subject text,
    message text NOT NULL,
    status text DEFAULT 'new', -- 'new', 'read', 'replied'
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- Insert Sample Data for Notices
INSERT INTO notices (title, content, is_pinned, author) VALUES
('홈페이지 리뉴얼 안내', '안녕하세요, 휴메카입니다.<br>고객님들의 편의를 위해 홈페이지를 새롭게 리뉴얼하였습니다.<br>앞으로 더 나은 서비스를 제공하기 위해 노력하겠습니다.', true, '관리자'),
('2025년 설 연휴 고객센터 운영 안내', '설 연휴 기간 동안 고객센터 운영이 일시 중단됩니다.<br>단, 긴급 장애 처리는 24시간 정상 운영됩니다.<br>새해 복 많이 받으세요.', false, '관리자'),
('서버 정기 점검 안내 (1/15)', '안전한 서비스 제공을 위해 1월 15일 02:00 ~ 04:00 서버 점검이 진행될 예정입니다.<br>작업 시간 동안 일시적인 접속 순단이 발생할 수 있습니다.', false, '기술지원팀');

-- Insert Sample Data for FAQs
INSERT INTO faqs (category, question, answer, sort_order) VALUES
('general', '서비스 신청은 어떻게 하나요?', '홈페이지 상단의 [서비스] 메뉴에서 원하시는 상품을 선택하신 후, [상담 신청] 버튼을 통해 접수해 주시면 담당자가 연락드립니다.', 1),
('technical', '서버 접속이 안됩니다.', '서버 접속이 안될 경우, 먼저 로컬 네트워크 상태를 확인해 주세요. 문제가 지속되면 기술지원센터(02-418-4442)로 연락 부탁드립니다.', 1),
('billing', '세금계산서 발행은 언제 되나요?', '세금계산서는 결제 완료 후 익일 오전 중으로 등록된 이메일로 자동 발행됩니다.', 1),
('service', '유지보수 범위는 어디까지인가요?', '기본 유지보수는 하드웨어 장애 처리 및 네트워크 관제를 포함합니다. OS 및 애플리케이션 관리는 별도의 매니지드 서비스를 신청하셔야 합니다.', 1);
