-- ========================================
-- HUMECCA 전체 관리 시스템 데이터베이스 스키마
-- ========================================

-- 기존 테이블 정리
DROP TABLE IF EXISTS product_plans CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS company_history CASCADE;
DROP TABLE IF EXISTS terms CASCADE;
DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS inquiries CASCADE;
DROP TABLE IF EXISTS notices CASCADE;
DROP TABLE IF EXISTS faqs CASCADE;

-- ========================================
-- 1. 상품 관리 테이블
-- ========================================

-- 상품 카테고리 (메인)
CREATE TABLE products (
  id bigint generated by default as identity primary key,
  category text NOT NULL,           -- 'idc', 'vpn', 'security', 'solution'
  subcategory text,                 -- 'hosting', 'colocation', 'ddos' 등
  name text NOT NULL,
  slug text UNIQUE,
  description text,
  icon text,
  active boolean DEFAULT true,
  sort_order integer DEFAULT 1,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- 상품 플랜 (상세)
CREATE TABLE product_plans (
  id bigint generated by default as identity primary key,
  product_id bigint REFERENCES products(id) ON DELETE CASCADE,
  plan_name text NOT NULL,
  plan_id text,
  price text,
  period text DEFAULT '월',
  badge text,
  summary text,
  cpu text,
  ram text,
  storage text,
  traffic text,
  speed text,
  sites text,
  users text,
  features text,
  os_options text,
  license_info text,
  active boolean DEFAULT true,
  popular boolean DEFAULT false,
  sort_order integer DEFAULT 1,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- ========================================
-- 2. 회사 연혁 테이블
-- ========================================

CREATE TABLE company_history (
  id bigint generated by default as identity primary key,
  year integer NOT NULL,            -- 2025, 2024 등
  month integer,                    -- 1-12, NULL이면 연도만
  title text NOT NULL,
  description text,
  sort_order integer DEFAULT 1,     -- 같은 연도/월 내 순서
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- ========================================
-- 3. 약관 관리 테이블
-- ========================================

CREATE TABLE terms (
  id bigint generated by default as identity primary key,
  type text NOT NULL UNIQUE,        -- 'privacy', 'service', 'location'
  title text NOT NULL,
  content text NOT NULL,            -- HTML 형식 지원
  version text DEFAULT '1.0',
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- ========================================
-- 4. 고객사 로고 관리 테이블
-- ========================================

CREATE TABLE customers (
  id bigint generated by default as identity primary key,
  name text NOT NULL,
  logo_url text,                    -- 로고 이미지 URL
  website text,
  sort_order integer DEFAULT 1,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- ========================================
-- 5. 문의 관리 테이블
-- ========================================

CREATE TABLE inquiries (
  id bigint generated by default as identity primary key,
  name text NOT NULL,
  email text NOT NULL,
  phone text,
  subject text NOT NULL,
  message text NOT NULL,
  reply text,                       -- 관리자 답변
  status text DEFAULT 'pending',    -- 'pending', 'replied', 'closed'
  is_read boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  replied_at timestamp with time zone
);

-- ========================================
-- 6. 공지사항 테이블
-- ========================================

CREATE TABLE notices (
  id bigint generated by default as identity primary key,
  title text NOT NULL,
  content text NOT NULL,            -- HTML 형식 지원
  author text DEFAULT 'HUMECCA',
  views integer DEFAULT 0,
  is_pinned boolean DEFAULT false,  -- 상단 고정
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- ========================================
-- 7. FAQ 테이블
-- ========================================

CREATE TABLE faqs (
  id bigint generated by default as identity primary key,
  category text,                    -- 'general', 'technical', 'billing' 등
  question text NOT NULL,
  answer text NOT NULL,
  sort_order integer DEFAULT 1,
  views integer DEFAULT 0,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- ========================================
-- 인덱스 생성 (성능 최적화)
-- ========================================

CREATE INDEX idx_products_category ON products(category);
CREATE INDEX idx_products_active ON products(active);
CREATE INDEX idx_product_plans_product_id ON product_plans(product_id);
CREATE INDEX idx_product_plans_active ON product_plans(active);
CREATE INDEX idx_company_history_year ON company_history(year);
CREATE INDEX idx_company_history_active ON company_history(active);
CREATE INDEX idx_terms_type ON terms(type);
CREATE INDEX idx_customers_active ON customers(active);
CREATE INDEX idx_inquiries_status ON inquiries(status);
CREATE INDEX idx_notices_active ON notices(active);
CREATE INDEX idx_notices_pinned ON notices(is_pinned);
CREATE INDEX idx_faqs_category ON faqs(category);
CREATE INDEX idx_faqs_active ON faqs(active);

-- ========================================
-- Row Level Security (RLS) 활성화
-- ========================================

ALTER TABLE products ENABLE row level security;
ALTER TABLE product_plans ENABLE row level security;
ALTER TABLE company_history ENABLE row level security;
ALTER TABLE terms ENABLE row level security;
ALTER TABLE customers ENABLE row level security;
ALTER TABLE inquiries ENABLE row level security;
ALTER TABLE notices ENABLE row level security;
ALTER TABLE faqs ENABLE row level security;

-- ========================================
-- RLS 정책 (전체 공개 - 추후 인증 추가 가능)
-- ========================================

-- Products
CREATE POLICY "Public access to products" ON products FOR ALL USING (true);
CREATE POLICY "Public access to product_plans" ON product_plans FOR ALL USING (true);

-- Company History
CREATE POLICY "Public access to company_history" ON company_history FOR ALL USING (true);

-- Terms
CREATE POLICY "Public access to terms" ON terms FOR ALL USING (true);

-- Customers
CREATE POLICY "Public access to customers" ON customers FOR ALL USING (true);

-- Inquiries
CREATE POLICY "Public access to inquiries" ON inquiries FOR ALL USING (true);

-- Notices
CREATE POLICY "Public access to notices" ON notices FOR ALL USING (true);

-- FAQs
CREATE POLICY "Public access to faqs" ON faqs FOR ALL USING (true);

-- ========================================
-- 초기 데이터 삽입
-- ========================================

-- 기본 약관 데이터
INSERT INTO terms (type, title, content, version) VALUES
('privacy', '개인정보처리방침', '<p>개인정보처리방침 내용이 여기에 들어갑니다.</p>', '1.0'),
('service', '이용약관', '<p>이용약관 내용이 여기에 들어갑니다.</p>', '1.0'),
('location', '위치정보 이용약관', '<p>위치정보 이용약관 내용이 여기에 들어갑니다.</p>', '1.0');

-- 기본 상품 카테고리
INSERT INTO products (category, subcategory, name, slug, active, sort_order) VALUES
('idc', 'hosting', '서버 호스팅', 'server-hosting', true, 1),
('vpn', 'vpn-service', 'VPN 전용선', 'vpn-dedicated', true, 2),
('security', 'ddos', 'DDoS 방어', 'ddos-protection', true, 3),
('solution', 'homepage', '맞춤형 홈페이지', 'custom-homepage', true, 4);

-- ========================================
-- 9. 간편 신청서 테이블 (Guest Application)
-- ========================================
CREATE TABLE applications (
  id bigint generated by default as identity primary key,
  product_type text,                -- 'hosting', 'vpn' 등
  product_name text,                -- 'HP ProLiant DL160 Gen10' 등
  company_name text,
  contact_person text NOT NULL,
  email text,
  phone text NOT NULL,
  memo text,
  status text DEFAULT 'pending',    -- 'pending', 'contacting', 'completed', 'cancelled'
  ip_address text,                  -- 스팸 추적용
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

CREATE INDEX idx_applications_status ON applications(status);
CREATE INDEX idx_applications_created_at ON applications(created_at);
ALTER TABLE applications ENABLE row level security;
CREATE POLICY "Public insert access to applications" ON applications FOR INSERT WITH CHECK (true);
CREATE POLICY "Admin read access to applications" ON applications FOR SELECT USING (true);
CREATE POLICY "Admin update access to applications" ON applications FOR UPDATE USING (true);

-- ========================================
-- 8. 웹 로그 (접속 통계) 테이블
-- ========================================

CREATE TABLE web_logs (
  id bigint generated by default as identity primary key,
  page_url text NOT NULL,
  visitor_ip text,                  -- IP 주소 (개인정보 이슈 시 마스킹 처리 권장)
  user_agent text,
  device_type text,                 -- 'desktop', 'mobile', 'tablet'
  referrer text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

CREATE INDEX idx_web_logs_created_at ON web_logs(created_at);
CREATE INDEX idx_web_logs_page_url ON web_logs(page_url);

ALTER TABLE web_logs ENABLE row level security;
CREATE POLICY "Public insert access to web_logs" ON web_logs FOR INSERT WITH CHECK (true);
CREATE POLICY "Admin read access to web_logs" ON web_logs FOR SELECT USING (true);


-- 완료 메시지
SELECT 'Database schema created successfully!' as status;
