const fs = require('fs');
const path = require('path');

const targetFile = 'f:/onedrive/OneDrive - 휴메카/08. homepage/sub_cloud_intro.html';

// Image Source Paths (generated by AI)
const imgDiagramSrc = 'C:/Users/ideac/.gemini/antigravity/brain/ac0ba905-7263-474f-be71-3c9290381083/cloud_diagram_final_1765280068410.png';
const imgLineupSrc = 'C:/Users/ideac/.gemini/antigravity/brain/ac0ba905-7263-474f-be71-3c9290381083/server_types_iso_1765280125293.png';

// Destination Paths in Project
const imgDir = 'f:/onedrive/OneDrive - 휴메카/08. homepage/images';
const imgDiagramDest = path.join(imgDir, 'cloud_service_diagram_final.png');
const imgLineupDest = path.join(imgDir, 'server_lineup_iso.png');

// 1. Copy Images
if (!fs.existsSync(imgDir)) fs.mkdirSync(imgDir, { recursive: true });
try {
    fs.copyFileSync(imgDiagramSrc, imgDiagramDest);
    fs.copyFileSync(imgLineupSrc, imgLineupDest);
    console.log('Copied new images successfully.');
} catch (e) {
    console.error('Error copying images:', e);
}

// 2. Build the "Full" Content HTML
if (fs.existsSync(targetFile)) {
    const fullContent = `
            <!-- 1. Service Overview Header -->
            <div class="content-header">
                <h2>서비스 개요</h2>
                <p>
                    <strong style="color:#d92e2e;">High Performance Cloud Server</strong>는 기업 비즈니스에 최적화된 고성능 컴퓨팅 환경을 제공합니다.<br>
                    물리적 서버 구매 없이 웹 인터페이스를 통해 즉시 서버를 생성하고, 필요에 따라 유연하게 자원을 확장할 수 있습니다.<br>
                    안정적인 인프라와 강력한 보안, 합리적인 비용으로 비즈니스 혁신을 가속화하세요.
                </p>
            </div>

            <!-- 2. Server Line-up (Visual Section) -->
            <div class="content-section">
                <div class="section-title">서버 라인업</div>
                <div style="background: #ffffff; padding: 40px; border-radius: 16px; border: 1px solid #e2e8f0; text-align: center; margin-bottom: 30px;">
                    <img src="images/server_lineup_iso.png" alt="Server Lineup" style="max-width: 80%; height: auto; margin-bottom: 20px;">
                    <div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px; text-align: center;">
                        <div>
                            <h4 style="color: #1e293b; margin-bottom: 8px;">Standard Server</h4>
                            <p style="font-size: 14px; color: #64748b;">일반적인 웹 호스팅 및<br>어플리케이션 개발 용도</p>
                        </div>
                        <div>
                            <h4 style="color: #dc2626; margin-bottom: 8px;">High Performance</h4>
                            <p style="font-size: 14px; color: #64748b;">고성능 CPU/Memory 기반<br>트래픽이 많은 서비스 용도</p>
                        </div>
                        <div>
                            <h4 style="color: #1e293b; margin-bottom: 8px;">DB Server</h4>
                            <p style="font-size: 14px; color: #64748b;">대용량 메모리와 I/O에<br>최적화된 데이터베이스 용도</p>
                        </div>
                    </div>
                </div>
                <p style="color: #475569; line-height: 1.6; background: #f8fafc; padding: 20px; border-radius: 8px;">
                    <strong>2세대/3세대 서버 구성:</strong> 최신 Intel Skylake/Cascade Lake 기반의 프로세서를 탑재하여 기존 대비 40% 이상 향상된 성능을 제공합니다.<br>
                    모든 서버는 고속 SSD 스토리지를 기본 제공하며, 워크로드에 따라 Local Disk 방식과 Network Volume 방식을 선택할 수 있습니다.
                </p>
            </div>

            <!-- 3. Core Features (6 Cards) -->
            <div class="content-section">
                <div class="section-title">서비스 특장점</div>
                <div class="feature-grid">
                    <div class="feature-card">
                        <div class="icon"><i class="fas fa-expand-arrows-alt"></i></div>
                        <h3>유연한 확장성</h3>
                        <p>비즈니스 상황에 맞춰 자원 즉시 변경<br>Auto Scaling 지원</p>
                    </div>
                    <div class="feature-card">
                        <div class="icon"><i class="fas fa-shield-alt"></i></div>
                        <h3>탁월한 안정성</h3>
                        <p>99.9% 가용성 보장 (SLA)<br>자동 장애 복구 (HA)</p>
                    </div>
                    <div class="feature-card">
                        <div class="icon"><i class="fas fa-bolt"></i></div>
                        <h3>신속한 배포</h3>
                        <p>다양한 OS 이미지 제공<br>수 분 내 서버 생성 완료</p>
                    </div>
                    <div class="feature-card">
                        <div class="icon"><i class="fas fa-coins"></i></div>
                        <h3>비용 효율성</h3>
                        <p>초기 투자 비용 Zero<br>합리적인 종량제 요금</p>
                    </div>
                    <div class="feature-card">
                        <div class="icon"><i class="fas fa-tachometer-alt"></i></div>
                        <h3>강력한 성능</h3>
                        <p>최신 Intel Xeon 프로세서<br>고성능 SSD 기본 탑재</p>
                    </div>
                    <div class="feature-card">
                        <div class="icon"><i class="fas fa-lock"></i></div>
                        <h3>엔터프라이즈 보안</h3>
                        <p>VM별 무료 방화벽 제공<br>IPS/WAF 보안 연동 가능</p>
                    </div>
                </div>
            </div>

            <!-- 4. Service Architecture Diagram (Fixed Image) -->
            <div class="content-section">
                <div class="section-title">서비스 구성도</div>
                <div style="background: #ffffff; padding: 0; border-radius: 16px; border: 1px solid #e2e8f0; overflow: hidden; text-align: center;">
                    <!-- 'object-position' can help trim header/footer if needed, but generated image should be white bg -->
                    <img src="images/cloud_service_diagram_final.png" alt="Cloud Architecture" style="width: 100%; height: auto; display: block; background:white;">
                </div>
                <p style="margin-top: 15px; color: #64748b; font-size: 14px; text-align: center;">
                    사용자 트래픽이 방화벽과 로드밸런서를 거쳐 웹/DB 서버로 안전하게 배분되는 구조입니다.
                </p>
            </div>

            <!-- 5. Detailed Specification (Meticulous Table) -->
            <div class="content-section">
                <div class="section-title">상품 상세 사양</div>
                <div style="overflow-x:auto; margin-top: 20px;">
                    <table class="cloud-content table" style="width:100%; border-collapse:collapse; background:white; margin:0;">
                        <thead>
                            <tr>
                                <th style="width:25%; text-align:left; background:#f1f5f9; padding:15px; border-bottom:2px solid #cbd5e1;">구분</th>
                                <th style="text-align:left; background:#f1f5f9; padding:15px; border-bottom:2px solid #cbd5e1;">주요 사양 및 기능</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td style="padding:15px; border-bottom:1px solid #e2e8f0; font-weight:600; color:#1e293b;">프로세서 (CPU)</td>
                                <td style="padding:15px; border-bottom:1px solid #e2e8f0; color:#475569;">
                                    Intel® Xeon® Platinum/Gold Series<br>
                                    최대 3.0GHz Turbo Boost 지원
                                </td>
                            </tr>
                            <tr>
                                <td style="padding:15px; border-bottom:1px solid #e2e8f0; font-weight:600; color:#1e293b;">메모리 (Memory)</td>
                                <td style="padding:15px; border-bottom:1px solid #e2e8f0; color:#475569;">
                                    DDR4 ECC Registered DIMM<br>
                                    2GB ~ 256GB까지 다양한 용량 구성 가능
                                </td>
                            </tr>
                            <tr>
                                <td style="padding:15px; border-bottom:1px solid #e2e8f0; font-weight:600; color:#1e293b;">스토리지 (Storage)</td>
                                <td style="padding:15px; border-bottom:1px solid #e2e8f0; color:#475569;">
                                    All-Flash SSD / High-Performance HDD<br>
                                    IOPS 보장형 볼륨 (최대 20,000 IOPS) 제공
                                </td>
                            </tr>
                            <tr>
                                <td style="padding:15px; border-bottom:1px solid #e2e8f0; font-weight:600; color:#1e293b;">네트워크 (Network)</td>
                                <td style="padding:15px; border-bottom:1px solid #e2e8f0; color:#475569;">
                                    40Gbps 이중화 인프라<br>
                                    Server당 10Gbps Network Interface 제공
                                </td>
                            </tr>
                            <tr>
                                <td style="padding:15px; border-bottom:1px solid #e2e8f0; font-weight:600; color:#1e293b;">운영체제 (OS)</td>
                                <td style="padding:15px; border-bottom:1px solid #e2e8f0; color:#475569;">
                                    CentOS, Ubuntu, Debian, RedHat Enterprise Linux<br>
                                    Windows Server 2016 / 2019 / 2022 (국/영문)
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            
            <div style="height:80px;"></div>
`;

    let html = fs.readFileSync(targetFile, 'utf8');

    // Replace Main Content
    const mainRegex = /<main class="cloud-content">([\s\S]*?)<\/main>/;

    if (mainRegex.test(html)) {
        html = html.replace(mainRegex, `<main class="cloud-content">${fullContent}</main>`);
        fs.writeFileSync(targetFile, html, 'utf8');
        console.log('Fully updated sub_cloud_intro.html with enriched content matching the screenshot.');
    }
}
