/**
 * HUMECCA 호스팅 상품 데이터
 * Generated by Admin: 2025. 12. 10. 오전 12:32:23
 */

var hostingProducts = [
    {
        "id": "eco_01",
        "name": "이코노미",
        "price": "89,000",
        "period": "월",
        "badge": "",
        "summary": "입문용 가성비 서버",
        "popular": true,
        "isActive": true,
        "sortOrder": 1,
        "specs": {
            "cpu": "Xeon E-2224 (4 Core)",
            "ram": "16GB DDR4",
            "storage": "256GB NVMe SSD",
            "traffic": "1Gbps Shared"
        },
        "features": [
            "CentOS / Ubuntu 지원",
            "기본 보안 방화벽 제공",
            "24/365 기술 지원"
        ]
    },
    {
        "id": "host-01",
        "name": "호스팅",
        "price": "99999",
        "period": "월",
        "badge": "",
        "summary": "",
        "isActive": true,
        "popular": true,
        "sortOrder": 1,
        "specs": {
            "cpu": "4",
            "ram": "8",
            "storage": "1000",
            "traffic": "10"
        },
        "features": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "56"
        ]
    },
    {
        "id": "biz_01",
        "name": "비즈니스",
        "price": "199,000",
        "period": "월",
        "badge": "BEST",
        "summary": "중소규모 비즈니스 최적화",
        "popular": true,
        "isActive": true,
        "sortOrder": 2,
        "specs": {
            "cpu": "Xeon Silver 4210 (10 Core)",
            "ram": "64GB DDR4",
            "storage": "1TB NVMe SSD",
            "traffic": "10Gbps Ready"
        },
        "features": [
            "RAID 1 데이터 보호",
            "웹 방화벽(WAF) 무료",
            "초기 세팅비 무료"
        ]
    },
    {
        "id": "ent_01",
        "name": "엔터프라이즈",
        "price": "399,000",
        "period": "월",
        "badge": "POWER",
        "summary": "고성능 DB/웹 서버용",
        "popular": true,
        "isActive": true,
        "sortOrder": 3,
        "specs": {
            "cpu": "AMD EPYC 7302 (16 Core)",
            "ram": "128GB DDR4",
            "storage": "2TB NVMe RAIDO",
            "traffic": "Dedicated Line"
        },
        "features": [
            "전담 엔지니어 배정",
            "VIP 기술 지원",
            "네트워크 이중화"
        ]
    }
];

if (typeof localStorage !== 'undefined' && localStorage.getItem("hostingProducts")) {
    try {
        hostingProducts = JSON.parse(localStorage.getItem("hostingProducts"));
    } catch (e) {
        console.error("Local data parsing error", e);
    }
}