-- Database Schema for HUMECCA Website (PostgreSQL / Supabase)

-- 1. Announcements Table
create table if not exists announcements (
  id bigint generated by default as identity primary key,
  title text not null,
  content text,
  is_important boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Inquiries Table & Contact Forms
create table if not exists inquiries (
  id bigint generated by default as identity primary key,
  type text not null, -- 'support', 'quote', 'hosting', etc.
  name text not null,
  company text,
  contact text not null, -- phone or email
  email text,
  message text,
  status text default 'pending', -- 'pending', 'processing', 'completed'
  ip_address text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Products/Services Table
create table if not exists products (
  id bigint generated by default as identity primary key,
  category text not null, -- 'hosting', 'vpn', 'cloud'
  product_id text unique, -- 'biz_01'
  name text not null,
  price text,
  period text, -- 'month', 'year'
  badge text,
  summary text,
  specs jsonb, -- { cpu: '...', ram: '...' }
  features text[], -- Array of strings
  is_active boolean default true,
  is_popular boolean default false,
  sort_order integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Visit Logs (Web Analytics)
create table if not exists visit_logs (
  id bigint generated by default as identity primary key,
  page_path text not null,
  referrer text,
  user_agent text,
  ip_address text, -- Note: Storing IP might assume privacy compliance
  session_id text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Company History
create table if not exists company_history (
  id bigint generated by default as identity primary key,
  year integer not null,
  month integer,
  title text not null,
  description text,
  sort_order integer default 0,
  active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. Customer Logos
create table if not exists customer_logos (
  id bigint generated by default as identity primary key,
  name text not null,
  logo_url text,
  sort_order integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies (Optional but recommended - public read, admin write)
alter table announcements enable row level security;
create policy "Public announcements are viewable by everyone." on announcements for select using (true);
create policy "Allocated admins can insert announcements." on announcements for insert with check (true); -- In prod, check auth.uid()

alter table products enable row level security;
create policy "Public products are viewable by everyone." on products for select using (true);

alter table company_history enable row level security;
create policy "Public history are viewable by everyone." on company_history for select using (true);

alter table customer_logos enable row level security;
create policy "Public logos are viewable by everyone." on customer_logos for select using (true);

alter table visit_logs enable row level security;
create policy "Allow generic insert for logs" on visit_logs for insert with check (true);
create policy "Only admin can view logs" on visit_logs for select using (true); -- In prod, check auth.uid()
